
{'date': 'Mon Nov 11 2019 10:55:29.847 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 18
  style={"opacity": 0},vai=self._ajuda)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Nov 11 2019 10:56:58.321 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 18
  style={"opacity":0},vai=self._ajuda)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Nov 11 2019 10:59:46.723 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 18
  style={"opacity":0},vai=self._ajuda)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Nov 11 2019 11:00:03.89 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 33
    fc.ajuda()
TypeError: 'Elemento' object is not callable
'''},
{'date': 'Mon Nov 11 2019 11:00:31.308 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 33
    fc.ajuda()
TypeError: 'Elemento' object is not callable
'''},